version: '3.8'

services:
  composer_install:
    image: composer
    volumes:
      - ./src:/app
    command: sh -c "composer install --ignore-platform-reqs"

  php:
    build:
      context: bin/php8
    restart: always
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
      - ./.env:/var/.env

  nginx:
    build:
      context: bin/nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./bin/nginx:/etc/nginx/conf.d

  db:
    build:
      context: bin/mysql8
    volumes:
      - ${MYSQL_INITDB_DIR}:/docker-entrypoint-initdb.d
      - ./storage/mysql:/var/lib/mysql
    restart: always
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  phpmyadmin:
    build:
      context: bin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
      MEMORY_LIMIT: ${MEMORY_LIMIT}
    ports:
      - '${HOST_MACHINE_PMA_PORT}:80'
